APPLICATION_STATE = "MENU"

MENU_STATE = "MENU"
CALIBRATION_STATE = "CALIBRATION"
VISUALISE_STATE = "VISUALISATION"

MAIN_WINDOW_NAME = "Main menu"
CALIBRATION_WINDOW_NAME = "Calibration"
VISUALISE_WINDOW_NAME = "Visualisation"
